"""changed attend

Revision ID: c76ab428242a
Revises: a67c615e8778
Create Date: 2024-04-05 20:54:07.110244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76ab428242a'
down_revision: Union[str, None] = 'a67c615e8778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations', sa.Column('atten', sa.Boolean(), nullable=False))
    op.drop_column('event_registrations', 'attended')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations', sa.Column('attended', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('event_registrations', 'atten')
    # ### end Alembic commands ###
